# Dockerfile.dev
FROM node:20

WORKDIR /app

# Copy only package files first to leverage caching
COPY package*.json ./

RUN npm install

# Now copy the rest of the source code
COPY . .

EXPOSE 4200

CMD ["npm", "run", "start"]
